### ISSUE TITLE
Dashboard in subpath

### ISSUE THREAD

**Issue by FStefanni** [emqx/emqx-dashboard5#1848]
Hi,

I need to serve the dashboard under an url subpath.
I have searched the options, but found none.
Is there a way to achieve this goal?

I also want to serve the dashboard behind a reverse proxy (traefik).

I have done some tries, but nothing worked...
any help please?

PS: I am using the docker official image of EMQX, in a local docker environment.

Thank you,
regards

**Comment by ysfscream** [comment]
Hi @FStefanni,

I understand that you are looking to serve the EMQX dashboard under a specific subpath using a reverse proxy. Utilizing Nginx for this can be a good option. Here's a basic guide on how you can set this up:

1. **Ensure** that both Nginx and EMQX are properly installed in your environment.
   
2. **Navigate** to your Nginx configuration file, generally located at `/etc/nginx/sites-available/` or `/etc/nginx/sites-enabled/`, and define a new server block for setting up the reverse proxy. Inside this block, use the `location` directive to specify the subpath and reverse proxy settings.

3. Below is a simplified example configuration that proxies the EMQX Dashboard to a "subpath":

   ```nginx
   server {
       listen 80;
       
       server_name yourdomain.com;
       
       location /subpath/ {
           proxy_pass http://EMQX_DASHBOARD_IP:EMQX_DASHBOARD_PORT/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
       }
   }
   ```

   In this configuration:
   - Replace `EMQX_DASHBOARD_IP` and `EMQX_DASHBOARD_PORT` with the actual IP address and port number of your EMQX Dashboard.
   - Replace `yourdomain.com` with your actual domain name.

4. **Save** the configuration file and **test** the configuration with the command:

   ```bash
   nginx -t
   ```

5. If there are no errors, **restart** Nginx to apply the new configuration:

   ```bash
   sudo systemctl restart nginx
   ```

6. **Finally**, you should be able to access your EMQX dashboard via "http://yourdomain.com/subpath".

I hope this helps!

**Comment by FStefanni** [comment]
Hi,

thank you for your answer. I have been finally able to figure out what was wrong.
Basically:
1. No need to set `EMQX_DASHBOARD__LISTENERS__HTTPS__PROXY_HEADER=true`
2. If the root path does not ends with `/`, we have to force it

The second point is achieved in Traefik by using the trick of a redirect.
Here follow the relevant part in my docker compose, if other people will need the same solution:

```yaml
labels:
- "traefik.enable=true"
- "traefik.http.services.emqx.loadbalancer.server.scheme=http"
- "traefik.http.services.emqx.loadbalancer.server.port=18083"
- "traefik.http.routers.emqx.entrypoints=websecure"
- "traefik.http.routers.emqx.tls=true"
- "traefik.http.routers.emqx.tls.certresolver=myresolver"
- "traefik.http.routers.emqx.tls.domains[0].main=myserver.local"
- "traefik.http.routers.emqx.rule=(Host(`myserver.local`) || Host(`10.23.16.15`)) && (PathPrefix(`/mypath`))"
- "traefik.http.routers.emqx.middlewares=emqx-chain"
- "traefik.http.middlewares.emqx-chain.chain.middlewares=emqx-redirect,emqx-strip"
- "traefik.http.middlewares.emqx-strip.stripprefix.prefixes=/mypath/"
- "traefik.http.middlewares.emqx-strip.stripprefix.forceslash=true"
- "traefik.http.middlewares.emqx-redirect.redirectregex.regex=^https://(.*)/mypath$$"
- "traefik.http.middlewares.emqx-redirect.redirectregex.replacement=https://$${1}/mypath/"
```

Now I can access with both:
* `https://myserver/mypath`: by using the redirect trick
* `https://myserver/mypath/`: normal strip prefix

Regards
