### ISSUE TITLE
Allow disabling the requirements of default password changes via environment variables

### ISSUE THREAD

**Issue by lafirest** [emqx/emqx-dashboard5#623]
Now dashboard forces make an ask for password change when a user logs in with the default password, which is so good but not developer friendly, perhaps we could allow this to be disabled via an environment variable?

**Comment by ysfscream** [comment]
YES. We did this, but only in the dashboard development environment, I'm not quite sure how to do this shi in emqx's development environment either.

**Comment by Kinplemelon** [comment]
This requirement has been mentioned by @JimMoen before, in fact, it is now up to the front-end to determine whether the user is using the default password or not, if you need to implement the requirements you mentioned there are two ways
1. the default password field is provided directly by the backend, which can set this variable to false directly in the development environment
2. simply provide a variable for the development environment, the front end gets this variable and when this variable is true, the password change prompt does not pop up

I think the first method would be better, what do you think?

**Comment by Rory-Z** [comment]
The first method is good, let's do it !

**Comment by JimMoen** [comment]
I'll try it next week. @lafirest @Rory-Z

**Comment by ysfscream** [comment]
THANKS @JimMoen

**Comment by JimMoen** [comment]
Passing through and load envs to front-end requiring restart vue service.
But you can actually circumvent this problem by setting a default password for EMQX that is different from `public` through shell environment variables.
You can also use other tools such as [direnv](https://direnv.net/) to add independent environment variables for different directories.

```bash
$ cat .envrc                                                
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .envrc
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ export PROFILE="emqx-enterprise";
   2   │ export EMQX_DASHBOARD__DEFAULT_PASSWORD="public123";
```

**Comment by ysfscream** [comment]
Thanks @JimMoen
